version: '3.8'

services:
  tempfox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tempfox-app
    environment:
      # AWS credentials can be passed via environment variables
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    volumes:
      # Mount AWS credentials directory (optional)
      - ~/.aws:/home/tempfox/.aws:ro
      # Mount current directory for development
      - .:/app
    working_dir: /app
    command: ["--help"]
    
  tempfox-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tempfox-dev
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    volumes:
      - ~/.aws:/home/tempfox/.aws:ro
      - .:/app
    working_dir: /app
    command: ["bash"]
    stdin_open: true
    tty: true
